stages: 
  - sandbox

.salesforce-container:
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y python3-venv python3 ca-certificates curl gnupg jq
    - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    - apt-get install -y nodejs
    - npm install --global @salesforce/cli@latest
    - sf version --verbose --json

createAndRefreshSandboxCLI:
  stage: sandbox
  cache: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $SANDBOX
      when: always
    - when: never
  allow_failure: false
  script:
    - echo $PRODUCTION_AUTH_URL | sf org login sfdx-url --set-default --sfdx-url-stdin
    - source ./scripts/bash/create_sandbox.sh
  tags: 
    - aws,prd,us-west-2

createAndRefreshSandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SANDBOX && $LICENSE
      when: manual
    - when: never
  allow_failure: false
  script:
    - python3 -m venv "venv"
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install simple-salesforce
    - python ./scripts/python/create_sandbox.py --sandbox "$SANDBOX" --license "$LICENSE" --class "$CLASS" --group "$GROUP" --url $PRODUCTION_AUTH_URL
  tags: 
    - aws,prd,us-west-2

querySandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SANDBOX
      when: manual
    - when: never
  allow_failure: false
  script:
    - python3 -m venv "venv"
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install simple-salesforce
    - python ./scripts/python/query_sandbox.py --sandbox "$SANDBOX" --url $PRODUCTION_AUTH_URL
  tags: 
    - aws,prd,us-west-2

deleteSandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' && $SANDBOX
      when: manual
    - when: never
  allow_failure: false
  script:
    - python3 -m venv "venv"
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install simple-salesforce
    - python ./scripts/python/delete_sandbox.py --sandbox "$SANDBOX" --url $PRODUCTION_AUTH_URL
  tags: 
    - aws,prd,us-west-2
