stages: 
  - sandbox

# Update to install the desired version of the Salesforce CLI
# on your preferred docker container
.salesforce-container:
  image: ubuntu:latest

  before_script:
    - apt-get update
    - apt-get install -y python3-venv python3
    - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    - apt-get install -y nodejs
    - npm install --global @salesforce/cli@latest
    - sf version --verbose --json
    - python3 ./authenticate_sfdx.py --alias PRODUCTION --url $PRODUCTION_AUTH_URL
    - python3 -m venv "venv"
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install simple-salesforce

createAndRefreshSandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
      when: always
    - when: never
  allow_failure: true
  script:
    - python ./create_sandbox.py --alias "PRODUCTION" --sandbox "$SANDBOX"
  tags: 
    - aws,prd,us-west-2

querySandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
      when: manual
    - when: never
  allow_failure: true
  script:
    - python ./query_sandbox.py --alias "PRODUCTION" --sandbox "$SANDBOX"
  tags: 
    - aws,prd,us-west-2

deleteSandbox:
  extends: .salesforce-container
  stage: sandbox
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
      when: manual
    - when: never
  allow_failure: true
  script:
    - python ./delete_sandbox.py --alias "PRODUCTION" --sandbox "$SANDBOX"
  tags: 
    - aws,prd,us-west-2
