---
name: Check Stale Sandboxes

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Salesforce CLI and Simple Salesforce
        run: |
          apt-get update
          apt-get install -y python3-venv python3
          npm install --global @salesforce/cli@latest
          sf version --verbose --json
          python3 -m venv "venv"
          source venv/bin/activate
          pip install --upgrade pip
          pip install simple-salesforce

      - name: Check for Stale Sandboxes
        env:
          PRODUCTION_AUTH_URL: ${{ secrets.PRODUCTION_AUTH_URL }}
        run: |
          python ./scripts/python/query_stale_sandboxes.py --url $PRODUCTION_AUTH_URL
