---
name: Create/Refresh Sandbox - Salesforce CLI

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: Name of the sandbox to create or refresh
        required: true
        type: string

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Salesforce CLI and JQ
        run: |
          apt-get update
          apt-get install -y curl jq
          npm install --global @salesforce/cli@latest
          sf version --verbose --json

      - name: Create or refresh the Sandbox
        env:
          PRODUCTION_AUTH_URL: ${{ secrets.PRODUCTION_AUTH_URL }}
          SANDBOX: ${{ github.event.inputs.sandbox }}
        run: |
          source ./scripts/bash/create_sandbox.sh
